# Generated by Django 3.2.5 on 2021-08-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=512)),
                ('code', models.TextField()),
                ('content', models.CharField(blank=True, default='', max_length=128)),
                ('recognition', models.CharField(blank=True, default='', max_length=128)),
            ],
        ),
    ]
