# Generated by Django 3.2.5 on 2021-08-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snippet',
            new_name='IDCode',
        ),
    ]
