# Generated by Django 3.2.5 on 2021-08-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0002_rename_snippet_idcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idcode',
            old_name='url',
            new_name='img_url',
        ),
    ]
