# Generated by Django 3.2.5 on 2021-08-05 03:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0003_rename_url_idcode_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcode',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, default=list, size=None),
        ),
    ]
