# Generated by Django 3.2.5 on 2021-08-05 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0008_alter_idcode_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idcode',
            name='content',
        ),
    ]
