# Generated by Django 3.2.5 on 2021-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0009_remove_idcode_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcode',
            name='content',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
