# Generated by Django 3.2.5 on 2021-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('js_app', '0010_idcode_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idcode',
            name='recognition',
            field=models.TextField(),
        ),
    ]
